services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_BACKEND_USER}:${DB_BACKEND_PASSWORD}@backend_db:5432/${DB_BACKEND_NAME}?schema=public
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      backend_db:
        condition: service_healthy


  # frontend:
  #   build: ./mobile
  #   container_name: frontend
  #   ports:
  #     - "${FRONTEND_PORT}:8081"
  #     - "${FRONTEND_PORT_2}:8082"
  #     - "${FRONTEND_PORT_3}:8083"
  #   volumes:
  #     - ./mobile:/app
  #     - /app/node_modules
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     EXPO_DEV_SERVER_PORT: 8081
  #     EXPO_DEV_SERVER_HOST: 0.0.0.0
  #   command: >
  #     sh -c "npx expo start --tunnel --port 8081 --dev-client"

  # PostgreSQL pour le backend
  backend_db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_BACKEND_USER}
      POSTGRES_PASSWORD: ${DB_BACKEND_PASSWORD}
      POSTGRES_DB: ${DB_BACKEND_NAME}
    ports:
      - "5432:5432"
    volumes:
      - backend_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_BACKEND_USER} -d ${DB_BACKEND_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # pgAdmin pour gérer la base de données PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "8080:80"
    depends_on:
      - backend_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  backend_db_data:
  pgadmin_data: