services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      DB_BACKEND_USER: ${DB_BACKEND_USER}
      DB_BACKEND_PASSWORD: ${DB_BACKEND_PASSWORD}
      DB_BACKEND_NAME: ${DB_BACKEND_NAME}
      DB_BACKEND_HOST: ${DB_BACKEND_HOST}
      DB_BACKEND_PORT: ${MYSQL_PORT}
    depends_on:
      - backend_db


  frontend:
    build: ./frontend
    container_name: frontend-dev
    ports:
      - "${FRONTEND_PORT}:8081"
      - "${FRONTEND_PORT_2}:8082"
      - "${FRONTEND_PORT_3}:8083"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      EXPO_DEV_SERVER_PORT: 8081
      EXPO_DEV_SERVER_HOST: 0.0.0.0
    command: >
      sh -c "npx expo start --tunnel --port 8081 --dev-client"

  # MySQL pour le backend
  backend_db:
    image: mysql:8.0
    container_name: backend-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_BACKEND_NAME}
      MYSQL_USER: ${DB_BACKEND_USER}
      MYSQL_PASSWORD: ${DB_BACKEND_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - backend_db_data:/var/lib/mysql

  # phpMyAdmin pour gérer la base de données
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${DB_BACKEND_HOST}
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - backend_db

volumes:
  backend_db_data: